import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header/Header";
import MovieDisplay from "../components/MovieDisplay";
import Navbar from "../components/Navbar";
import requests from "../utils/requests";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.png" />
      </Head>

      <Header />
      <Navbar />
      <MovieDisplay results={props.results} />
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      results: request.results,
    },
  };
}
